---
- name: Configuring apache2 using child playbooks
  hosts: all
  tasks:
   - name: Call multiple child playbooks for apache2
     include: "{{item}}"
     with_items:
      - install.yml
      - edit_index.yml
      - restart.yml
      - check_url_response.yml


