---
- name: Implementing handlers
  hosts: all
  tasks:
   - name: Instal apache2
     apt:
      name: apache2
      state: present
      update_cache: yes
     notify: Check url response
   - name: Edit the index.html file
     copy:
      content: "Welcome to HBC new Home page"
      dest: /var/www/html/index.hml
     notify: Restart apache
  handlers:
   - name: Restart apache
     service:
      name: apache2
      state: restarted
   - name: Check url response
     uri:
      url: "{{item}}"
      status_code: 200
     with_items:
      - http://172.31.19.176
      - http://172.31.25.184
      - http://172.31.91.151


...
