---
- name: Error Hanlding
  hosts: all
  tasks:
   - block:
      - name: Install git using apt
        apt:
         name: git
         state: present
         update_cache: yes
     rescue:
      - name: Install git uisng yum
        yum:
         name: git
         state: present
         update_cache: yes
...
