---
- name: Configuring tomcat
  hosts: all
  tasks:
    - name: Install tomcat9
      apt:
        name: tomcat9
        state: present
    - name: Copy the tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9
    - name: Change port of tomcat form 8080 to 9090
      replace:
        regexp: 9090
        replace: 8080
        path: /etc/tomcat9/server.xml
    - name: Check response of tomcat on server1
      uri:
        url: http://172.31.25.184:8080
        status_code: 200
    - name: Check reposne of tomcat on server2
      uri:
        url: http://172.31.31.127:8080
        status_code: 200
...


