---
- name: Create multiple users and copy files into users home dir
  hosts: all
  tasks:
   - name: Create user
     user:
      name: "{{item.a}}"
      password: "{{item.b}}"
      home: "{{item.c}}"
     with_items:
      - {a: Anu,b: hbc,c: /home/Anu}
      - {a: Ravi,b: hbc,c: /home/ubuntu/Ravi}
   - name: Copy files into users home dir
     copy:
      src: "{{item.a}}"
      dest: "{{item.b}}"
     with_items:
      - {a: /etc/passwd,b: /home/Anu}
      - {a: /etc/group,b: /home/ubuntu/Ravi}
...
