---
- name: Implementing docker compsoe using ansible
  hosts: all
  tasks:
   - name: Create a mysql container
     docker_container:
      name: mydb
      image: mysql
      env:
       MYSQL_ROOT_PASSWORD: krishna

   - name: Create a wordpress container
     docker_container:
      name: mywordpress
      image: wordpress
      ports:
       - 8989:80
      links:
       - mydb:mysql

